id: /subscriptions/6b82bbc7-26a3-4a88-94c7-f28fe5baca8b/resourceGroups/rg-stock-options-manager/providers/Microsoft.App/containerapps/ca-stock-options-manager
identity:
  type: None
location: Sweden Central
name: ca-stock-options-manager
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: ca-stock-options-manager.greenfield-bff0f81c.swedencentral.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 8000
      targetPortHttpScheme: null
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
    registries: null
    revisionTransitionThreshold: null
    runtime: null
    secrets: null
    service: null
    targetLabel: ''
  customDomainVerificationId: B70954373E1D434DAEBDE7C41D061163B83854EF9F059AC91C7A573912448BA2
  delegatedIdentities: []
  environmentId: /subscriptions/6b82bbc7-26a3-4a88-94c7-f28fe5baca8b/resourceGroups/rg-stock-options-manager/providers/Microsoft.App/managedEnvironments/cae-stock-options-manager
  eventStreamEndpoint: https://swedencentral.azurecontainerapps.dev/subscriptions/6b82bbc7-26a3-4a88-94c7-f28fe5baca8b/resourceGroups/rg-stock-options-manager/containerApps/ca-stock-options-manager/eventstream
  latestReadyRevisionName: ca-stock-options-manager--muu0xyd
  latestRevisionFqdn: ca-stock-options-manager--muu0xyd.greenfield-bff0f81c.swedencentral.azurecontainerapps.io
  latestRevisionName: ca-stock-options-manager--muu0xyd
  managedEnvironmentId: /subscriptions/6b82bbc7-26a3-4a88-94c7-f28fe5baca8b/resourceGroups/rg-stock-options-manager/providers/Microsoft.App/managedEnvironments/cae-stock-options-manager
  outboundIpAddresses:
  - 20.240.28.167
  - 20.240.28.184
  - 20.240.28.187
  - 20.240.29.51
  - 74.241.193.90
  - 74.241.192.157
  - 74.241.192.45
  - 74.241.193.154
  - 74.241.192.111
  - 74.241.193.34
  - 9.223.20.105
  - 135.116.6.186
  - 9.223.21.30
  - 9.223.218.210
  - 135.116.14.134
  - 9.223.143.243
  - 9.223.9.149
  - 74.241.137.85
  - 74.241.139.161
  - 74.241.138.64
  - 74.241.136.237
  - 9.223.21.119
  - 9.223.10.153
  - 9.223.225.145
  - 9.223.220.233
  - 74.241.136.44
  - 9.223.87.134
  - 74.241.139.29
  - 9.223.20.250
  - 9.223.20.145
  - 20.240.38.142
  - 20.240.38.235
  - 20.240.37.255
  - 20.240.37.231
  - 74.241.204.139
  - 74.241.204.246
  - 74.241.202.17
  - 74.241.200.59
  - 74.241.205.78
  - 74.241.203.192
  - 9.223.237.26
  - 9.223.246.165
  - 74.241.209.91
  - 74.241.211.241
  - 9.223.245.238
  - 135.116.14.86
  - 9.223.173.128
  - 9.223.237.22
  - 4.225.86.27
  - 9.223.75.69
  - 9.223.245.208
  - 9.223.237.31
  - 9.223.45.114
  - 9.223.24.231
  - 74.241.210.170
  - 9.223.246.185
  - 9.223.16.144
  - 135.116.37.178
  - 9.223.247.36
  - 9.223.18.163
  - 4.225.244.11
  patchingMode: Automatic
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - env:
      - name: AZURE_AI_PROJECT_ENDPOINT
        value: https://ai-innovation-labs-vs.openai.azure.com
      - name: MODEL_DEPLOYMENT
        value: gpt-5.4-mini
      - name: AZURE_OPENAI_API_KEY
        value: 3HN5DGpP3vnksg6PcbLKCeT9qQV6nVgoByvKPACRuc6Eekk3TKILJQQJ99CCACfhMk5XJ3w3AAAAACOGMGqq
      image: ghcr.io/dsanchor/stock-options-manager:latest
      imageType: ContainerImage
      name: ca-stock-options-manager
      volumeMounts:
        - volumeName: data-volume
          mountPath: /app/data
        - volumeName: logs-volume
          mountPath: /app/logs
      resources:
        cpu: 1.0
        ephemeralStorage: 4Gi
        memory: 2Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 1
      minReplicas: 1
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes:
      - name: data-volume
        storageName: optionsdata
        storageType: AzureFile
      - name: logs-volume
        storageName: optionslogs
        storageType: AzureFile
  workloadProfileName: Consumption
resourceGroup: rg-stock-options-manager
systemData:
  createdAt: '2026-03-27T23:23:52.9710362'
  createdBy: sancheski@gmail.com
  createdByType: User
  lastModifiedAt: '2026-03-27T23:23:52.9710362'
  lastModifiedBy: sancheski@gmail.com
  lastModifiedByType: User
type: Microsoft.App/containerApps
